### ISSUE TITLE
Match.endIndex() is exclusive

### ISSUE THREAD

**Issue by danielnaber** [knowitall/openregex#10]
When Match.endIndex() returns 3, it's actually the token at index 2 which is the last matching token. In this context, I think it would be more natural if the endIndex really pointed to the last matching token. Of course, then `endIndex - startIndex` will be zero for matches of length one...

Alternatively, the javadoc could be reworded, it currently says: "the index of the last token matched."

**Comment by schmmd** [comment]
I think the behavior is what I want.  It's performs the same as `List.sublist` for example ([javadoc](http://docs.oracle.com/javase/7/docs/api/java/util/List.html#subList%28int, int%29).  However, the comment is certainly confusing.

I try and use the word "end" for the exclusive end index and "last" for the index of the final item.

**Comment by schmmd** [comment]
4e73882f8f52c1777c3685095e7fb267c0b64303
