### ISSUE TITLE
RegularExpressionParsers  should be public?

### ISSUE THREAD

**Issue by akhudek** [knowitall/openregex#15]
I assume that word and character in RegularExpressionParsers are intended to be used as part of the public interface? It seems that since RegularExpressionParsers is itself not marked public, it makes it impossible to access the word and character fields.  At least it does when trying to access it via clojure.

**Comment by schmmd** [comment]
Good point, thank you!  Nobody else has hit this because they are only for example.  This has been fixed.

I don't know about clojure-scala interop, but https://github.com/knowitall/openregex-scala exists too.
