### ISSUE TITLE
idea for performance optimization

### ISSUE THREAD

**Issue by danielnaber** [knowitall/openregex#8]
Here's an idea for an optimization: RegularExpression.find() contains this loop:

```
for (int i = start; i < tokens.size(); i++) ...
```

This seems to loop even when no match is possible. For example, if my pattern is "abc", the minimum length of a text that can match is 3. So if my input text is shorter than the minimum pattern length, I can stop immediately. More general, I don't have to iterate up to `tokens.size()` but only to `tokens.size()-minPatternLen`.

Finding the minimum pattern length shouldn't be too difficult, e.g. Expression.Star is always 0, Expression.Or is the minimum of both sub expressions etc.

**Comment by schmmd** [comment]
Great idea--would you like to submit a pull request?  We could add a minimumMatchingLength method to each expression and use it in `find`.

**Comment by danielnaber** [comment]
Sorry, looks like I won't have time to provide a patch.

**Comment by schmmd** [comment]
Ok, we'll see if I get around to it ;-)

**Comment by schmmd** [comment]
Daniel, can I ask if/how you are using OpenRegex?

Peace.  Michael

**Comment by danielnaber** [comment]
I was considering using it for LanguageTool (https://github.com/languagetool-org/languagetool), which finds errors by using patterns. However, currently it seems we need back references and non-greediness, while the better worst-case performance of Thompson is probably not relevant.

**Comment by schmmd** [comment]
`for (int i = start; i < tokens.size(); i++)` should have been `for (int i = start; i <= tokens.size(); i++)` as well.  Otherwise a pattern with a minimum matching length of 0 couldn't match an empty list of tokens.

**Comment by schmmd** [comment]
I have a pull request in for this https://github.com/knowitall/openregex/pull/9.  I'm back from vacation ;-)
